Fifth
zipnikitin/testGuru pull request #6
Opened 2021-06-17 18:23 UTC by zipnikitin

2021-06-18 12:43 UTC, VidgarVii requested changes

2021-06-18 12:43 UTC, VidgarVii commented on testGuru/app/models/user.rb
> +    Test.joins('JOIN users ON tests.author_id = users.id').where( level: current_level )
задачку про "пройденные тесты" правильно решать через соединительную таблицу
нужно добавить модель, к примеру `Result` или `TestsUser` и соответсвенную таблицу (`tests_users` или `results`)... или `TestPassage` и `test_passages`
в общем нужны "промежуточная модель" и "соединительная таблица"
такая таблица ("соединительная") обычно в минимальном виде хранит два внешних ключа на таблицы, которые соединяет
когда пользователь проходит тест в этой таблице должна появляться запись содержащая соответсвенно ай-ди этого пользователя и ай-ди пройденного теста
(подробней можешь посмотреть в документации к рельсам про соединительные модели, таблицы)

в простейшем варианте, который в общем-то очень часто используется, в соединительной таблице всего два поля (кроме ай-ди)
в нашем случае это будут `user_id`, `test_id` - если в таблице существует запись для пары тест-юзер, то юзер этот тест проходил (при прохождении теста нужно будет создать такую запись), если записи нет, то тест не пройден
с помощью этого механизма можно хранить информацию о прохождении любого количества тестов любым количеством пользователей

2021-06-18 12:43 UTC, VidgarVii commented on testGuru/app/models/test.rb
>      Test.joins('JOIN categories ON tests.category_id = categories.id').where(categories: { title: category_name }).order(type: :desc)
1 метод должен возвращать массив названий тестов. А не сами тесты
2 можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2021-06-18 12:43 UTC, VidgarVii commented on testGuru/app/models/statistic.rb
> +end
не понятно что-за статистика, которая не используется

2021-06-19 14:49 UTC, VidgarVii requested changes

2021-06-19 14:49 UTC, VidgarVii commented on testGuru/app/models/result.rb
> +
тут не большая не стыковка

2021-06-19 14:49 UTC, VidgarVii commented on testGuru/db/seeds.rb
> +results = Result.create!([{ user_id: users[0].id, test_id: tests[0].id }])
нет у тебя такой модели Result. Сиды получается не протестированы

2021-06-19 14:49 UTC, VidgarVii commented on testGuru/db/schema.rbold
> +end
схема не актуальная. название таблиц не согласуется с названиями моделей и с маграциями

2021-06-19 23:52 UTC, zipnikitin commented on testGuru/db/schema.rbold
> +end
Да, ведь это не schema.rb, а schema.rbOLD))

2021-06-19 23:52 UTC, zipnikitin commented on testGuru/db/schema.rbold
> +end
schema.rb рядом

2021-06-21 09:55 UTC, merged